In [20]:
import numpy as np
import random as rm
from numpy.linalg import matrix_power

states = ["Work","Bed","Gym"]
transitionName = [["WW","WB","WG"],["BW","BB","BG"],["GW","GB","GG"]]
transitionMatrix = np.array([[0.5,0.4,0.1],[0.3,0.2,0.5],[0.7,0.1,0.2]])
State0Matrix=np.array([1,0,0])

In [27]:
print("Transition matrix to the third power:") 
print(matrix_power(transitionMatrix, 3))
print("")
State3Matrix=(State0Matrix).dot(matrix_power(transitionMatrix, 3))
print(State3Matrix)

print("")
print("On day 3, the probability of the state being bed is :")
print((State3Matrix[1]*100), "%")

Transition matrix to the third power:
[[0.496 0.261 0.243]
 [0.504 0.289 0.207]
 [0.468 0.288 0.244]]

[0.496 0.261 0.243]

On day 3, the probability of the state being bed is :
26.100000000000005 %
